openapi: '3.0.2'
info:
  title: API MyGram
  description: API like Instagram. This API is Final Project Koinworks
  version: '1.0'
servers:
  - url: https://localhost:3000
components:
  schemas:
    User:
      type: object
      properties:
        age:
          type: integer
          minimum: 9
        email:
          type: string
          uniqueItems: true
        password:
          type: string
          minLength: 6
        username:
          type: string
          uniqueItems: true
      required:
        - age
        - email
        - password
        - username
    FailedResponse:
      type: object
      properties:
        error:
          type: string

paths:
  /users/register:
    post:
      tags:
      - users
      description: Register new user
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

      responses:
        '201':
          description: Success register new user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
        '400':
          description: Failed register new user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /users/login:
    post:
      tags:
      - users
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /users:
    put:
      tags:
      - users
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    delete:
      tags:
      - users
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /photos:
    post:
      tags:
      - photos
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    get:
      tags:
      - photos
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /photos/{photoId}:
    put:
      tags:
      - photos
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    delete:
      tags:
      - photos
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /comments:
    post:
      tags:
      - comments
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    get:
      tags:
      - comments
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /comments/{commentId}:
    put:
      tags:
      - comments
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    delete:
      tags:
      - comments
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /socialmedias:
    post:
      tags:
      - socialmedias
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    get:
      tags:
      - socialmedias
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /socialmedias/{socialMediaId}:
    put:
      tags:
      - socialmedias
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    delete:
      tags:
      - socialmedias
      responses:
        '200':
          description: OK
        '400':
          description: ERROR