openapi: '3.0.2'
info:
  title: API MyGram
  description: API like Instagram. This API is Final Project Koinworks
  version: '1.0'
servers:
  - url: https://localhost:3000
components:
  schemas:
    User:
      type: object
      properties:
        age:
          type: integer
          minimum: 9
        email:
          type: string
          uniqueItems: true
        password:
          type: string
          minLength: 6
        username:
          type: string
          uniqueItems: true
      required:
        - age
        - email
        - password
        - username
    ResponseRegisterUser:
      type: object
      properties:
        age:
          type: integer
        email:
          type: string
        id:
          type: integer
        username:
          type: string
    ResponseUpdateUser:
      type: object
      properties:
        age:
          type: integer
        email:
          type: string
        id:
          type: integer
        username:
          type: string
        updated_at:
          type: string
    LoginUpdateUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password     
    FailedResponse:
      type: object
      properties:
        error:
          type: string
    SuccessResponseMessage:
      type: object
      properties:
        message:
          type: string
    Photo:
      type: object
      properties:
        title:
          type: string
        caption:
          type: string
        photo_url:
          type: string
      required:
        - title
        - photo_url
    ResponseAddPhoto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        caption:
          type: string
        photo_url:
          type: string
        user_id:
          type: integer
        created_at:
          type: string
    ResponseGetPhoto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        caption:
          type: string
        photo_url:
          type: string
        user_id:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        User:
          type: object
          properties:
            email:
              type: string
            username:
              type: string
    ResponseUpdatePhoto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        caption:
          type: string
        photo_url:
          type: string
        user_id:
          type: integer
        updated_at:
          type: string
    Comment:
      type: object
      properties:
        message:
          type: string
        photo_id:
          type: integer
      required:
        - message
    ResponseCreateComment:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        photo_id:
          type: integer
        user_id:
          type: integer
        created_at:
          type: string
    ResponseGetComments:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        photo_id:
          type: integer
        user_id:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        User:
          type: object
          properties:
            id:
              type: integer
            email: 
              type: string
            password:
              type: string
        Photo:
          type: object
          properties:
            id:
              type: integer
            title:
              type: string
            caption:
              type: string
            photo_url:
              type: string
            user_id:
              type: integer
    ResponseUpdateComment:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        photo_id:
          type: integer
        user_id:
          type: integer
        updated_at:
          type: string
    SocialMedia:
      type: object
      properties:
        name:
          type: string
        social_media_url:
          type: string
      required:
        - name
        - social_media_url
    ResponseCreateSocialMedia:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        social_media_url:
          type: string
        user_id: 
          type: integer
        date:
          type: string
    ResponseGetSocialMedias:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        social_media_url:
          type: string
        UserId: 
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        User:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            profil_image_url:
              type: string
    ResponseUpdateSocialMedia:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        social_media_url:
          type: string
        user_id: 
          type: integer
        updated_at:
          type: string

            
          
paths:
  /users/register:
    post:
      tags:
      - users
      description: Register new user
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

      responses:
        '201':
          description: Success register new user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseRegisterUser'
        '400':
          description: Failed register new user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /users/login:
    post:
      tags:
      - users
      description: Login user to get token
      summary: Login user to get token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/LoginUpdateUser'
      responses:
        '200':
          description: Success login user
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Failed login user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /users/{userId}:
    put:
      tags:
      - users
      description: Update data user by user id
      summary: Update data user by user id
      parameters:
        - required: true
          name: userId
          in: path
          description: user id 
          schema:
            type: integer
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/LoginUpdateUser'
      responses:
        '200':
          description: Success update data user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseUpdateUser'
        '400':
          description: Failed update data user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    delete:
      tags:
      - users
      description: Delete user by user id
      summary: Delete user by user id
      parameters:
        - required: true
          name: userId
          in: path
          description: user id 
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Success delete user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessResponseMessage'
        '400':
          description: Failed delete user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /photos:
    post:
      tags:
      - photos
      description: Add new photo
      summary: Add new photo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Photo'
      responses:
        '201':
          description: Success add new photo
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseAddPhoto'
        '400':
          description: Failed register new user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    get:
      tags:
      - photos
      description: Get all photos 
      summary: Get all photos 
      responses:
        '200':
          description: Success get all photos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseGetPhoto'       
        '400':
          description: Failed get all photos
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /photos/{photoId}:
    put:
      tags:
      - photos
      description: Update data photo by photo id
      summary: Update data photo by photo id
      parameters:
        - required: true
          name: photoId
          in: path
          description: photo id 
          schema:
            type: integer
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Photo'
      responses:
        '200':
          description: Success update data photo
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseUpdatePhoto'
        '400':
          description: Failed update data photo
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    delete:
      tags:
      - photos
      description: Delete photo by photo id
      summary: Delete photo by photo id
      parameters:
        - required: true
          name: photoId
          in: path
          description: photo id 
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Success delete photo
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessResponseMessage'
        '400':
          description: Failed delete photo
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /comments:
    post:
      tags:
      - comments
      description: Add new comment
      summary: Add new comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Success add new comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseCreateComment'
        '400':
          description: Failed add new comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    get:
      tags:
      - comments
      description: Get all comments 
      summary: Get all comments 
      responses:
        '200':
          description: Success get all comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseGetComments'       
        '400':
          description: Failed get all comments
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /comments/{commentId}:
    put:
      tags:
      - comments
      description: Update comment by comment id
      summary: Update comment by comment id
      parameters:
        - required: true
          name: commentId
          in: path
          description: comment id 
          schema:
            type: integer
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Success update comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseUpdatePhoto'
        '400':
          description: Failed update comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    delete:
      tags:
      - comments
      description: Delete comment by comment id
      summary: Delete comment by comment id
      parameters:
        - required: true
          name: commentId
          in: path
          description: comment id 
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Success delete comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessResponseMessage'
        '400':
          description: Failed delete comment
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /socialmedias:
    post:
      tags:
      - socialmedias
      description: Add new social media
      summary: Add new social media
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialMedia'
      responses:
        '201':
          description: Success add new social media
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseCreateSocialMedia'
        '400':
          description: Failed add new social media
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    get:
      tags:
      - socialmedias
      description: Get all social medias 
      summary: Get all social medias 
      responses:
        '200':
          description: Success get all social medias
          content:
            application/json:
              schema:
                type: object
                properties:
                  social_medias:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResponseGetSocialMedias'       
        '400':
          description: Failed get all social media
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
  /socialmedias/{socialMediaId}:
    put:
      tags:
      - socialmedias
      description: Update socialmedia by socialmedia id
      summary: Update socialmedia by socialmedia id
      parameters:
        - required: true
          name: socialMediaId
          in: path
          description: socialmedia id 
          schema:
            type: integer
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/SocialMedia'
      responses:
        '200':
          description: Success update socialmedia
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ResponseUpdateSocialMedia'
        '400':
          description: Failed update socialmedia
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'
    delete:
      tags:
      - socialmedias
      description: Delete socialmedia by socialmedia id
      summary: Delete socialmedia by socialmedia id
      parameters:
        - required: true
          name: socialMediaId
          in: path
          description: socialmedia id 
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Success delete socialmedia
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessResponseMessage'
        '400':
          description: Failed delete socialmedia
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/FailedResponse'